### ISSUE TITLE
scp and ssh commands do not show the console output

### ISSUE THREAD

**Issue by reddyshyam** [saisandeepvaddi/ten-hands#178]
**OS**: Windows 10 Pro 64bit Insider build (19041.264) 20H1

**Where**: Desktop App

**Describe the bug**
When using OpenSSH scp or ssh, the console output which is visible on CMD or Powershell is not visible on app

**To Reproduce**
Run scp or ssh to check

**Expected behavior**
With scp, progress bar of upload to be shown. With SSH, console output shouuld be shown

**Screenshots**
![Screenshot_18May2020_161045](https://user-images.githubusercontent.com/12392746/82204338-56a7d980-9922-11ea-88e4-266aec3fb9f8.png)

**Additional context**

**Comment by saisandeepvaddi** [comment]
I think this one needs a different way. Right now we run tasks on local machine shell and return the output. But if we use remote machines, we might have to stream the output back to local machine's shell. It was in the plans since long time, I never got time to start on it.

I'll try to add it in here whenever I have time after current work is complete.
