### ISSUE TITLE
[FEATURE REQUEST] Can the last run output remain until task run again?

### ISSUE THREAD

**Issue by reddyshyam** [saisandeepvaddi/ten-hands#182]
**Is your feature request related to a problem? Please describe.**
At the moment there is no way to remember what was the output of a task run last

**Describe the solution you'd like**
It would be really helpful if the output remains until it ran the next time i.e. even after app is closed and re-opened. Timestamp of both start and complete will be good as well.

**Additional context**
May be not everyone would prefer this but this could a configuration option for users to decide

**Comment by saisandeepvaddi** [comment]
I do not save tasks output to database. Saving output of tasks may not be very performant because you can run dozens of tasks and tasks most of the time have massive amount of text. 

For example saving output of something like `$> cat huge_text_file.txt` will not be good to save in json db file or localStorage. Like you said, configuration option for task may be helpful. But if users start using that without thinking, it might end up crashing the app.

Will think about it.

**Comment by reddyshyam** [comment]
Thanks for considering Sai Sandeep. I just want the task's last run output, this will be overwritten by  task's next run. And also this option can be disabled by default in config if you think default enabling will cause issues. Users who need will then enable it.

**Comment by reddyshyam** [comment]
Also don't think its a good idea to put the logs into config file. May be another log txt file with outputs as task name delimited?

No rush, not so important but if implement will be very handy. :)
