### ISSUE TITLE
Search giving inconsistent results

### ISSUE THREAD

**Issue by reddyshyam** [saisandeepvaddi/ten-hands#188]
**OS**: Windows 10 Pro 64 bit 20H1 insider (19041.264)
**Where**: Desktop App

**Describe the bug**
Search giving inconsistent results

**To Reproduce**
Fewer characters giving more inaccurate results.

**Expected behavior**
No matter how many characters we type, results shold definitely show only those tasks matching those characters.

**Screenshots**

**Additional context**
![Screenshot_24May2020_211022](https://user-images.githubusercontent.com/12392746/82758444-3b4a3c00-9e04-11ea-8a04-c449e4df68ac.png)

As you can see in the above screenshot, **publ** matches just two of my tasks but app is returning more results which do not have any such occurances.

![Screenshot_24May2020_211451](https://user-images.githubusercontent.com/12392746/82758447-3c7b6900-9e04-11ea-9fcf-ff77c2e94cb4.png)

And again in the above screenshot, there aren't any task with that keyword searched (**test**) yet it lists so many. Hope this helps.

**Comment by reddyshyam** [comment]
I would also like to thank you for such a great feature added as I am sure it will he useful if one has plenty of tasks. Thank you. :)

**Comment by saisandeepvaddi** [comment]
Fuzzy search is intentional. When there are so many tasks and users actually don't remember exact words when tasks have very long names, fuzzy search includes similar results even if they don't have exact words in it. Think of it as a tiny search engine.

As long as the intentional results are on top, I'd like to keep search fuzzy. Also, the search is weighted. That is, task name and actual command has weight 2, while project name of the task has weight 1. I also didn't put limit for the number of results yet because if there are many tasks that contain `npm run`, we can't eliminate any of them.

Ten Hands uses [https://fusejs.io/examples.html#weighted-search](https://fusejs.io/examples.html#weighted-search)

Hope this clears up. I'll keep an eye on consistency of results, and improve.

**Comment by reddyshyam** [comment]
Hi Sai Sandeep,

I appreciate the concept and its wider use but it still confuses the users who are looking for a particular thing and see more results. I think this should be an option to the user if he wants just accurate results or fuzzy results, may be in the db again. 

I am not fussy (😀) about fuzzy so please feel free to close the ticket you think its generally correct.

**Comment by saisandeepvaddi** [comment]
Thats understandable. I'll revisit this issue on search results if any other users wish the same. I'll close this for now.
