### ISSUE TITLE
[FEATURE REQUEST] Any chance adding "sending a custom stop like ctrl+c" before stopping the task on hitting stop button please?

### ISSUE THREAD

**Issue by reddyshyam** [saisandeepvaddi/ten-hands#193]
**Is your feature request related to a problem? Please describe.**
I am trying to start a database via command line and I usually stop by sending ctrl+c signal. With our app, on hitting 'stop' button, looks like just terminates the task without any controlled shutdown of the process running.

**Describe the solution you'd like**
On hitting Stop button, if we can also send any custom triggers or commands (like ctrl+c or ctrl+d), will be great help to see the tasks complete more elegantly or normally.

**Comment by saisandeepvaddi** [comment]
I can send the kill command to use `SIGINT` (Ctrl + C) signal instead of `SIGTERM` signal (which is used currently) to kill the process. Even then, it will be similar to automatically sending `SIGINT` followed by `Y` for a node process. At the process level, both signals are used to terminate with addition to keyboard interrupt signal when used ctrl + c. 

AFAIK, Unless we use an actual terminal which has a prompt, using ctrl+c vs terminate signal doesn't affect process any differently.

So in your database example, being able to ctrl+c doesn't add anything more to stop gracefully. https://nodejs.org/api/process.html

Please let me know if you found any other resource that gives any extra info on process signals.

**Comment by reddyshyam** [comment]
Hi,

Thanks for getting back, I see what you mean. I have seen couple of articles about graceful exits (giving below for reference) but again those are for processes began using node.js. I have created another task which can send graceful exit command to database, so no worries. Thanks for looking into it.

https://hackernoon.com/graceful-shutdown-in-nodejs-2f8f59d1c357
https://flaviocopes.com/node-terminate-program/
https://glynnbird.tumblr.com/post/54739664725/graceful-server-shutdown-with-nodejs-and-express

Closing the ticket.
