### ISSUE TITLE
Display running task count in taskbar is not working

### ISSUE THREAD

**Issue by reddyshyam** [saisandeepvaddi/ten-hands#210]
**OS**: Windows 10 Pro 64bit 19041.450 20H1

**Where**: Desktop App 2.9.1

**Describe the bug**
Running task count is not displayed

**To Reproduce**
Start a task and check the taskbar

**Expected behavior**

**Screenshots**

**Additional context**
The below is my config.json

{
  "port": 5010,
  "enableTerminalTheme": true,
  "globalHotKey": "CommandOrControl+Alt+T",
  "showAppRunningTrayNotification": false,
  "showStatusBar": true,
  "taskViewStyle": "rows",
  "shell": "",
  "terminalRenderer" : "canvas",
  "hideToTrayOnClose" : false,
  "showTaskCountBadge" : true
}

**Comment by saisandeepvaddi** [comment]
should have worked in Windows 10 atleast as I've been using it for a while before releasing.

Anyway, I'll check it this asap. Meanwhile, could you please check if restarting probably fixes it as half the world's problems get fixed after a restart 😄.

Also can you add `log.log` file from `~/.ten-hands` folder which is the same folder where config.json file is.

I keep forgetting adding some kind of exception handling app like Sentry so that I'll know errors better. I'll probably release a patch to add Sentry this weekend.

**Comment by reddyshyam** [comment]
> should have worked in Windows 10 atleast as I've been using it for a while before releasing.
> 

Saw the screenshots on release log and expected it to work out of the box too. 

> Anyway, I'll check it this asap. Meanwhile, could you please check if restarting probably fixes it as half the world's problems get fixed after a restart 😄.
> 

Ha  ha! I wouldn't agree more but I tried that trick already with no joy. 😜 
> Also can you add `log.log` file from `~/.ten-hands` folder which is the same folder where config.json file is.
> 

Please find it attached. 
[log.log](https://github.com/saisandeepvaddi/ten-hands/files/5165991/log.log)

> I keep forgetting adding some kind of exception handling app like Sentry so that I'll know errors better. I'll probably release a patch to add Sentry this weekend.

Makes sense. Please do so, thank you.

**Comment by reddyshyam** [comment]
Hi Sai Sandeep, 

Thanks for releasing 2.10 and I am on it. Still cannot see the count on badge. Haven't disabled sentry. Please let me know if you need anything else.

**Comment by saisandeepvaddi** [comment]
I added sentry to project but didn't refactor the code to send me events
yet. Will be in future.

Also, I've sent this app to a couple of friends who use Windows 10, taskbar
is showing badge.

One thing that would cause this issue is your Windows Taskbar settings.
Could you please check if the following option is turned on?

*Right click on taskbar --> Taskbar Settings and make sure "Show badges on
taskbar buttons" option is on.*

[image: image.png]

**Comment by saisandeepvaddi** [comment]
![image](https://user-images.githubusercontent.com/13838175/95819216-7ab1f000-0cf3-11eb-92f6-e09ec320c39c.png)

**Comment by reddyshyam** [comment]
Hi Sai Sandeep,

Thanks for getting back. I think I got it all wrong. I was expecting the count in the tray area icon and not on the tab. 

![image](https://user-images.githubusercontent.com/12392746/95819790-66e2aa00-0d44-11eb-9a5f-3ee0bd8b5ad5.png)

Also I use small taskbar buttons option and so this ruled out anyway Windows feature wise.

Sorry for the trouble. Closing the ticket.

**Comment by saisandeepvaddi** [comment]
Oh, I didn't even know about small icons removing badges. 😁

Will check and try to add it to tray icons if it works. Thanks for letting
me know.
